<script>
    import i1 from "$lib/assets/l1.png";
    import i2 from "$lib/assets/l2.png";
    import i3 from "$lib/assets/l3.png";
    import i4 from "$lib/assets/l4.png";
  
    const desc = [
      {
        description:
          "As a solar energy company, installation is a critical aspect of our services. We offer a range of installation services to ensure that our customers' solar energy systems are installed correctly and safely. Our team of professionals is experienced and trained to handle all aspects of the installation process, from site assessment to commissioning. We use high-quality materials and equipment to ensure that our installations are of the highest quality and offer our customers the best possible value for their investment.",
        heading: "Installation",
        id: "l1",
        img: i1,
        pos: 1,
      },
      {
        description:
          " At our solar energy company, we are committed to providing our customers with the highest possible energy generation. We use the latest solar panel technology to ensure that our systems generate as much energy as possible, even in low-light conditions. Our solar panels are highly efficient and designed to maximize energy production, so our customers can enjoy significant savings on their energy bills.",
        heading: "Generation",
        id: "l2",
        img: i2,
        pos: 2,
      },
      {
        description:
          "Energy storage is an essential part of our solar energy services. Our company offers a range of energy storage solutions to help our customers store excess energy generated by their solar systems. Our storage solutions are highly efficient and designed to maximize energy retention, ensuring that our customers have access to energy when they need it most.",
        heading: "Storage and Efficiency",
        id: "l3",
        img: i3,
        pos: 3,
      },
      {
        description:
          " As a solar energy company, we understand the importance of monitoring the performance of our solar systems. That's why we offer app-based monitoring solutions that allow our customers to track their energy generation and consumption in real-time. Our app-based monitoring solutions are user-friendly and offer a range of features that make it easy for our customers to manage their solar energy systems.",
        heading: "Monitor and Control",
        id: "l4",
        img: i4,
        pos: 4,
      },
    ];
  </script>
  

  <div class='w-full  flex-col md:flex hidden bg-white'>
    <!-- {desc.map((val) => { -->
      
     {#each desc as val}
     <div
     class={`flex  m-5 items-end ${
       val.pos % 2 !== 0 ? "flex-row" : "flex-row-reverse"
     }`}
   >
     <img
       src={val.img}
       id={val.id}
       class="rounded-2xl  w-[40%]"
       alt=""
     />
     <div
       class={`flex text-black flex-col ${
         val.pos % 2 !== 0 ? "items-start" : "items-end text-end"
       }`}
     >
       <h1 class="mx-8 font-semibold text-4xl mb-3">{val.heading}</h1>
       <h1 class="mx-8 text-2xl font-thin leading-9">{val.description}</h1>
     </div>
   </div>
     {/each}
      
  
  </div>
  
  <div class="md:hidden flex items-center text-black bg-white my-8 px-0 justify-center ">
    <div class="flex flex-col  justify-center items-center">

      {#each desc as val}
      <div >
        <img
          src={val.img}
          id={val.id}
          class={`rounded-lg w-[80%] mx-5 ease-in duration-100 mt-10 mb-5`}
          alt=""
        />
        <div class="z-20 col-span-3  flex flex-col justify-center items-center sm:items-start">
          <div class="flex  flex-col justify-center">
            <h1 class="mx-8 font-semibold text-3xl">{val.heading}</h1>
            <h1 class="mx-8">{val.description}</h1>
          </div>
        </div>
      </div>
      {/each}
      <!-- {desc.map((val) => {
        return (
          <div key={val.id}>
            <Image
              src={val.img}
              id={val.id}
              className={`rounded-lg w-[80%] mx-5 ease-in duration-100 mt-10 mb-5`}
              alt=""
            />
            <div className="z-20 col-span-3  flex flex-col justify-center items-center sm:items-start">
              <div className="flex  flex-col justify-center">
                <h1 className="mx-8 font-semibold text-3xl">{val.heading}</h1>
                <h1 className="mx-8">{val.description}</h1>
              </div>
            </div>
          </div>
        );
      })} -->
    </div>
  </div>